### ISSUE TITLE
Tweepy: Create service to reconnect once Twitter connection breaks

### ISSUE THREAD

**Issue by MSnowman** [jimmyo15/TwitterAPIProject#64]
I need to create a service that determines when the connection to Twitter Streamer breaks and reconnects

1. Create a routine to count the number of documents in the mongodb tweet database.
2. Create Job to restart the twitter connection
3. Create a job that will initiate number 2 if number 1’s count has not changed after 5 minutes

**Comment by jimmyo15** [comment]
Completed.  Can review when ready.
