### ISSUE TITLE
AWS app_config update with tweepy path

### ISSUE THREAD

**Issue by MSnowman** [jimmyo15/TwitterAPIProject#69]
Jim - need you to add the following into the twitterappconfig.json S3 file.  I do not have access

{""streamer_script"":"python3  /home/ec2-user/TwitterAPIProject/tweepyStreamerApp.py"}

**Comment by jimmyo15** [comment]
@MSnowman 
Looks like the following need to be done, please confirm:
1. Include {"STREAMER_LOCATION":"/home/ec2-user/TwitterAPIProject/tweepyStreamApp.py"} in app config
2. Update pre-config to pick it up
3. Update views to reference that in the daemon process call

If so, I'll make all the changes tonight.  Want to make sure I've captured the necessary items.

**Comment by MSnowman** [comment]
Cool!  Thanks dude
