### ISSUE TITLE
Flask Web Dashboard: Turn Off Stream Button

### ISSUE THREAD

**Issue by MSnowman** [jimmyo15/TwitterAPIProject#76]
Need to create a button to turn off a stream on the StreamingDashboard page

**Comment by jimmyo15** [comment]
In the Utils directory there is functionality to find a process and kill it. Can be used by web service to accept input from UI and then kill the process.

**Comment by MSnowman** [comment]
@jimmyo15  thought there might be.  Cool will check it out.
