### ISSUE TITLE
Modify Filter Parameters

### ISSUE THREAD

**Issue by jimmyo15** [jimmyo15/TwitterAPIProject#92]
Need to modify the filter parameters so that we are only looking for company mentions, full company names, and cashtags of the company tickers.  We may miss some tweets as a result of this, but the result will be a lot fewer unrelated tweets.  Cashtag symbol = $, Mentions = @.

**Comment by MSnowman** [comment]
That may be too limiting. 

I am seeing tweets that have the following int them

NYSE:ABT which is the exchange and the ticker

**Comment by jimmyo15** [comment]
You’re right. We can include such terms in our filter, though. [‘$abt’, ‘nyse:abt’]
